### ISSUE TITLE
我有一个macOS的移植版本，纳西妲的鼠标指针，需要可以找我

### ISSUE THREAD

**Issue by Nickspace114514** [SamToki/Sam-Toki-Mouse-Cursors#2]
B站叫大无聊国国王

**Comment by SamToki** [comment]
你好，很抱歉这么迟才看到你的 issue 😂
如果你制作了这套鼠标指针的 macOS 移植版本，你可以在我的评论区发布资源链接，或者直接自行发布作品。记得标明这是移植版本，原作者「SAM TOKI STUDIO」，以及原作品的链接即可。
感谢你的支持！
