### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by pat-hwaki** [SamToki/Sam-Toki-Mouse-Cursors#4]
或许您需要详细声明一下什么源文件是CC BY-NC-SA 3.0的，什么源文件是GPLv3的，因为把所有文件都打上这两个license的话可能造成冲突，在于GPLv3是允许商用的，CC BY-NC-SA 3.0是不允许的。假设所有文件都被这样dual-license了，可能造成下游选取GPLv3继承造成CC BY-NC-SA  的无效化，感觉需要显式声明艺术文件比如那些pptx 为 CC BY-NC-SA 3.0。含有光标配置和映射的文件如inf 为GPLv3.

**Comment by SamToki** [comment]
您好，多谢提醒，我马上整改。
新声明会让 STMC.zip 及其中所有文件使用CC协议，其外的文件保留版权。
其实我之前有意识到这两个协议之间有矛盾之处但没去重视，看来我还需要学习一个
